# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Umer Butt
title: AI Engineer | Software Developer
email: mumertbutt@gmail.com
website: github.com/UmerTariq1


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  UmerTariq1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: umertariq1
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.youtube.com/watch?v=xvFZjo5PgG0
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Umer Butt, an AI Research Assistant at DFKI with expertise in Natural Language Processing and Machine Learning. I specialize in developing NLP-driven automation solutions and AI-powered systems. With a strong background in software development and AI engineering, I've worked on various projects involving RAG, LLMs, and information retrieval systems.

  I am most skilled in:  <mark> Python</mark> ,  <mark> NLP</mark>  ,  <mark> LLMs</mark>  ,  <mark> Data Science</mark>   and  <mark> Software Development</mark>  

content:

  - title: Experience 
    layout: list
    content:
      - layout: left
        title: DFKI
        link: https://www.dfki.de/web 
        sub_title: AI Research Assistant
        caption: April 2022 - Present
        description: | 
          - Developed and implemented NLP-driven  <mark> automation solutions</mark>   that processed over  <mark> 1000+</mark>   complex documents, reducing processing time for enterprise clients (e.g., Siemens, Beko).
          - Designed and built an AI-powered student assistant using  <mark> RAG</mark>  ,  <mark> LLMs</mark>  , and  <mark> OpenAI API</mark>  .
          - Collaborated on  <mark> AI model deployment pipelines</mark>  , ensuring scalability and optimization for real-world applications.
      
      - layout: left
        title: University Of Saarland
        link: https://sfb1102.uni-saarland.de
        sub_title: Software Developer
        caption: August 2023 - Present
        description: |
          - Led the development and optimization of a  <mark> Python Django</mark>  -based linguistic experiment platform for  <mark> 1000+</mark>   active users, launching  <mark> 10+</mark>   new experiments and maintaining  <mark> 5</mark>   existing projects with a focus on code quality and performance.
          - Ensured scalability and code quality by implementing  <mark> CI/CD</mark>   practices, optimizing backend performance, and improving query response time through effective database management ( <mark> SQL</mark>  ).
      
      - layout: left
        title: Love For Data
        link: https://www.lovefordata.com  
        sub_title: AI Engineer
        caption: December 2020 - September 2021
        description: |
          - Developed an  <mark> Information Retrieval system</mark>   for the banking sector, enabling access to  <mark> 10,000+</mark>   legal regulations with a  <mark> 34%</mark>   improvement in search relevance using Statistical Models and Transformer Deep Learning Models.
          - Built a  <mark> Query Recommendation module</mark>   using Document Clustering and NER, improving query accuracy by  <mark> 45%</mark>   and precision by  <mark> 30%</mark>  ; integrated  <mark> Elasticsearch </mark>  for efficient document indexing and real-time retrieval. 

      - layout: left
        title: Systems Limited
        link: https://www.systemsltd.com/
        sub_title: Software Engineer
        caption: June 2019 - November 2020
        description: |
          - Supervised a team on multiple projects, including customer offer promotion and delivery systems. Remodelled and optimised implementation, achieving a  <mark> 28%</mark>   improvement in performance and a  <mark> 7%</mark>   reduction in false recommendations. Worked on  <mark> Java</mark>   and  <mark> Sprint Boot</mark>  .


  - title: Education
    layout: list
    content:
      - layout: left
        title: Saarland University 
        link: https://www.uni-saarland.de/
        caption: October 2021 - Present
        sub_title: Master's in Language Science and Technology
        description: | 
          Thesis: Created datasets for Urdu and Roman Urdu Information Retrieval using MT model and built a transformer-based transliteration pipeline. Designed Dense Retrieval baselines with mT5 and deep learning models, addressing data scarcity and enabling low-resource IR advancements. 
      
      - layout: left
        title: FAST NUCES 
        link: https://nu.edu.pk/ 
        caption: July 2015 - June 2019
        sub_title: Bachelor's in Computer Science
        description: | 
          Thesis: Implemented a neural-based IR system with Elasticsearch, FAISS, and embeddings from Word2Vec, LSTM, and BERT as part of my Bachelor's thesis. Achieved 2nd position among 300 projects in a university-wide competition.

  - title: Publications
    layout: list
    content:
      - layout: left
        title: Enabling Low-Resource Language Retrieval - Establishing Baselines for Urdu MS MARCO
        sub_title: ECIR 2024
        link:  https://arxiv.org/abs/2412.12997
        description: | 
          Authors -  <mark> Umer Butt</mark>  , S.Varanasi, G.Neumann
          
          Focused on developing baselines for Urdu information retrieval using MS MARCO dataset. 

      - layout: left
        title: Cross-Linguistic Processing of Non-Compositional Expressions in Slavic Languages
        sub_title: Cog-Alex 2024
        link: https://aclanthology.org/2024.cogalex-1.10/
        description: |
          Authors - I.Zaitova, I.Stenger,  <mark> Umer Butt</mark>  , T.Avgustinova
          
          Investigated processing of non-compositional expressions across Slavic languages.

      - layout: left
        title: AutoQIR - Auto-Encoding Questions with Retrieval Augmented Decoding
        sub_title: RANLP 2023
        link: https://ieeexplore.ieee.org/abstract/document/10607132
        description: |
          Authors - S.Varanasi,  <mark> Umer Butt</mark>  , G.Neumann
          
          Developed novel approach for unsupervised passage retrieval and zero-shot question generation.

      - layout: left
        title: Spatial-Economic Analysis for Optimal Electric Vehicle Charging Station Placement
        sub_title: SASI-ITE 2024
        link: https://aclanthology.org/2023.ranlp-1.124.pdf
        description: |
          Authors - A.Maurya, C.Agnes, B.Baloch, S.Anwari,  <mark> Umer Butt</mark>   (equal contrib)
          
          Analyzed optimal placement strategies for EV charging stations using spatial-economic factors.

      - layout: left
        title: Fairy Tales / Children Stories of the World - Corpus Organization and Text Analytics
        sub_title: ICLAP 2021
        link: https://www.researchgate.net/publication/354381634_Classic_Fairy_Tales_Children_Stories_of_the_World_Corpus_Organization_and_Text_Analytics
        description: |
          Authors - Y.Khan,  <mark> Umer Butt</mark>  
          
          Created and analyzed a corpus of children's stories from various cultures.

  
  - title: Skills & Expertise
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Languages**: Python, Java, C, C++, JS, HTML, CSS, SQL, NoSQL
      - **Frameworks & Tools**: PyTorch, Pandas, Scikit-Learn, Huggingface, XGBoost, Git, MongoDB, ElasticSearch, TensorFlow
      - **Other Skills**: RAG, OpenAI API, Agile development, Data pipelines, Docker
      - **Soft Skills**: Problem-solving, Pattern Recognition, Clear Communication


  - title: Projects 
    layout: list 
    content:
      - layout: top-middle
        title: RAG LLM chatbot with external knowledge source
        link: https://github.com/UmerTariq1/RAG-LLM-External-Documents # Replace with your actual link
        quote: > 
          "This chatbot was a fun challenge to build! I learned a lot about integrating LLMs with external knowledge sources." 
        description: | 
          I learned several skills through this project, including:
           <mark> Python</mark>    |   <mark> Llama3</mark>    |  <mark> HuggingFace</mark>    |  <mark> Streamlit</mark>    |  <mark> RAGs</mark>    |  <mark> LLMs</mark>  
      
      - layout: top-middle
        title: Deep IR System Using Context-Aware Vector Representations
        # link: https://github.com/your-username/your-repo-name # Replace with your actual link
        quote: >
          "Improving information retrieval with deep learning is fascinating. This project helped me understand the power of contextual embeddings."
        description: |
          I learned several skills through this project, including:
           <mark> FAISS</mark>    |   <mark> LSTM</mark>    |   <mark> BERT</mark>    |   <mark> Elastic Search</mark>  
      
      - layout: top-middle
        title: Lyrics Generator using LLMs and its website
        link: https://github.com/UmerTariq1/Lyrics-Analysis-and-Generation
        quote: >
          "Generating creative text with AI is mind-blowing! Building this lyrics generator and its website was a rewarding experience."
        description: |
          I learned several skills through this project, including:
           <mark> Python</mark>    |   <mark> OpenAI API</mark>    |   <mark> Langchain API</mark>    |   <mark> Angular</mark>    |   <mark> Django</mark>   
      
      - layout: top-middle
        title: Click through Rate and No. of Clicks Prediction
        link: https://github.com/UmerTariq1/CTR-and-Clicks-Prediction-Using-Text-and-Numerical-Data
        quote: >
          "Predicting user behavior is a key aspect of online advertising. This project gave me valuable experience with machine learning for CTR prediction."
        description: |
          I learned several skills through this project, including:
           <mark> TFIDF</mark>    |   <mark> Word Embeddings</mark>    |   <mark> Linear Regression</mark>    |   <mark> RF</mark>   
      
      - layout: top-middle
        title: Extensive EDA and Modeling on Advertisement Dataset
        link: https://github.com/UmerTariq1/Advertisement-Sales-Prediction-EDA-and-Modeling
        quote: >
          "Exploratory data analysis is crucial for understanding any dataset. This project allowed me to dive deep into an advertising dataset and build predictive models."
        description: |
          I learned several skills through this project, including:
           <mark> Pandas</mark>    |   <mark> Numpy</mark>    |   <mark> Linear Regression</mark>    |   <mark> Matplotlib</mark>  
      
      - layout: top-middle
        title: Detailed Time Series Analysis on Solar Energy Dataset
        link: https://github.com/UmerTariq1/Time-Series-Data-Analysis
        quote: >
          "Analyzing time series data is essential in many fields, including renewable energy. This project helped me develop my skills in time series forecasting."
        description: |
          I learned several skills through this project, including:
           <mark> EDA</mark>    |   <mark> Arima</mark>    |   <mark> SArima models</mark>    |   <mark> Numpy</mark>    |   <mark> Pandas</mark>  

      - layout: top-middle
        title: Automated web scraping of Canada411.ca to extract contact records
        link: https://github.com/UmerTariq1/Canada411.ca-Scrapper
        quote: >
          "#TODO"
        description: |
          I learned several skills through this project, including:
           <mark> Python</mark>    |   <mark> beautifulSoup</mark>    |   <mark> Data Extraction</mark>  
          
      - layout: top-middle
        title: Automated web scraping of Canada411.ca to extract contact records
        link: https://github.com/UmerTariq1/Canada411.ca-Scrapper
        quote: >
          "Automated contact record extraction from Canada411.ca using Python and web scraping techniques."
        description: |
          I learned several skills through this project, including:
           <mark> Python</mark>    |   <mark> beautifulSoup</mark>    |   <mark> Data Extraction<mark>  




  - title: A Little More About Me
    layout: text
    content: | 
      When I'm not immersed in the world of code, you'll find me exploring the outdoors or enjoying some friendly competition. I love hiking and trekking through the beautiful Saarland countryside â€“ there's something truly refreshing about disconnecting and appreciating nature. I often bring my camera along to capture the scenery; photography is another passion of mine. I'm also a bit of a badminton enthusiast, and I always enjoy a good board game night with friends. It's the perfect way to unwind and socialize.

      Some other things I enjoy:
      - Gaming (cozy games and the occasional Valorant match when I'm feeling competitive)
      - Late night walks to clear my head and enjoy the quiet city
      - I also like to watch movies and TV shows
      - Trying new things and exploring different parts of landscapes - any recommendations are welcome! :) 
      - If I was not an engineer, I would be a professional photographer :) 

      
      Look at this cool image I took  
      ![Trees](images/cool1.jpg "Trees")
      ![Trees](images/cool2.jpg "Trees")
      ![Trees](images/cool3.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
